name: workflow for maven project

run-name: maven project workflow
on:
 push
 workflow_dispatch:

 jobs:
   maven-build-test:
   -name: Checkout code
    uses: actions/checkout@v5
   -name: Set up JAVA
    uses: actions/setup-java@4.6.0
    with:
      distribution: "oracle"
      java-version: "17"
    run:  mvn --batch-mode --update-snapshots verfiy
    run:  mkdir staging && cp target/*.jar staging
    uses: actions/upload-artifact@4.5.0
    with:
     name: Artifacts
     path: staging
